### ISSUE TITLE
No static binaries for arm32 and 64 

### ISSUE THREAD

**Issue by martiinezz** [Fahrj/reverse-ssh#14]
Would you be able to provide such binaries?

**Comment by Fahrj** [comment]
Sure, no hassle at all!

The only thing is that I'm not that much into ARM to know what's best, so I just compiled it for [armv7 (x86) and armv8 (x64)](https://github.com/Fahrj/reverse-ssh/releases/tag/v1.1.0).

Please let me know if that works for you, then I'll add them to all future releases as well.

**Comment by martiinezz** [comment]
Seems to be working on Armv7, thanks.
