### ISSUE TITLE
Code for SSH Session on Linux without a terminal

### ISSUE THREAD

**Issue by rumpelsepp** [Fahrj/reverse-ssh#4]
https://github.com/Fahrj/reverse-ssh/blob/master/ssh_session_unix.go#L58-L61

This code seems to be forgotten as we did the copy/pasta from the gliderlabs example. What should we do in this case? Error out?

**Comment by Fahrj** [comment]
I wouldn't really say forgotten, as I deliberately left it there to somewhat handle cases where the client does not request a PTY session, but might still be interested in port forwarding or such. You are right though, this should be prettified in terms of error handling and log output.

I will do some testing what cases actually trigger this code and what might be good approaches to handle these.
