### ISSUE TITLE
Other Architecture Builds

### ISSUE THREAD

**Issue by 6E006B** [Fahrj/reverse-ssh#5]
Maybe you could add some info to the README on how to compile it for other targets as well.
Something like:
"""
To compile for other architectures or OSs just add the desired line to the build target.
E.g. for linux/arm64:
```
CGO_ENABLED=0 GOARCH=arm64  GOOS=linux  go build -ldflags="$(LDFLAGS) -s -w" -o bin/reverse-ssh-arm64 .
```

A list of available targets can be obtained via `go tool dist list`.
"""

Or even allow specific target selection via environment variables or build targets.

**Comment by Fahrj** [comment]
Great idea!

I went ahead with 1f0f9a91e7846fe97df7e8b8289c35252d0841ec and added a plain build target that can be used to override `GOOS` and `GOARCH` as needed.
Implementing it this way felt a little more "clean" than adding even more targets for other operating systems or architectures.

I hope this works for you!

**Comment by 6E006B** [comment]
Nice, good solution!
There is just one thing slightly sub-optimal with this way - the resulting binary is always called `reverse-ssh`, with all the others having an explicit postfix, identifying its target.
As long as you know what you're doing this should be fine though.

**Comment by Fahrj** [comment]
I agree, adding a matching suffix would be a nice touch.

Nonetheless, I would consider cross-compiling somewhat _advanced_ and thus expect any user doing it to figure that the plain one is the correct binary.
